global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'metrics_collection'
    scheme: 'http'
    static_configs:
      - targets: [
        'localhost:5076',
      ]