version: "3.9"
services:
  yugabyte:
    image: yugabytedb/yugabyte:2.20.3.0-b68
    container_name: yugabyte
    hostname: yugabyte
    ports:
      - 7001:7000
      - 9000:9000
      - 15433:15433
      - 5433:5433
      - 9042:9042
    command: bin/yugabyted start
      --background=false
    networks:
      - public
networks:
  public:
    driver: bridge