apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app  
  ports:
      - nodePort: 32000
        protocol: TCP
        port: 8080

