version: "3.9"
services:
  cockroach-1:
    image: cockroachdb/cockroach:latest
    container_name: roach1
    hostname: roach1
    ports:
      - 26257:26257
      - 8080:8080
    command: start 
      --advertise-addr=roach1:26357
      --http-addr=roach1:8080
      --listen-addr=roach1:26357
      --sql-addr=roach1:26257
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    networks:
      - roachnet
  cockroach-2:
    image: cockroachdb/cockroach:latest
    container_name: roach2
    hostname: roach2
    depends_on:
      - cockroach-1
    ports:
      - 26258:26258
      - 8081:8081
    command: start 
      --advertise-addr=roach2:26357
      --http-addr=roach2:8081
      --listen-addr=roach2:26357
      --sql-addr=roach2:26258
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    networks:
      - roachnet
  cockroach-3:
    image: cockroachdb/cockroach:latest
    container_name: roach3
    hostname: roach3
    depends_on:
      - cockroach-2
    ports:
      - 26259:26259
      - 8082:8082
    command: start 
      --advertise-addr=roach3:26357
      --http-addr=roach3:8082
      --listen-addr=roach3:26357
      --sql-addr=roach3:26259
      --insecure
      --join=roach1:26357,roach2:26357,roach3:26357
    networks:
      - roachnet
networks:
  roachnet:
    driver: bridge